# Generated by Django 4.2.3 on 2023-07-07 20:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='due_back',
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(default=datetime.datetime(2023, 8, 6, 22, 25, 39, 940654), help_text='Date due to be returned')),
                ('returned_date', models.DateField(blank=True, help_text='Date book was returned', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.bookinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
