# Generated by Django 4.2.3 on 2023-07-08 11:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_alter_loans_book_alter_loans_due_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='book',
            new_name='book_instance',
        ),
        migrations.AlterField(
            model_name='loans',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 13, 35, 21, 817831), help_text='Date due to be returned'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
