# Generated by Django 4.2.3 on 2023-07-08 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_rename_book_loans_book_instance_alter_loans_due_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(default=datetime.datetime(2023, 8, 7, 13, 55, 57, 693203), help_text='Date due to be returned')),
                ('returned_date', models.DateField(blank=True, help_text='Date book was returned', null=True)),
                ('book_instance', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='catalog.bookinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Loans',
        ),
    ]
