# Generated by Django 4.2.3 on 2023-07-08 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_loan_options_alter_loan_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 17, 47, 42, 46650), help_text='Date borrowed'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 17, 47, 42, 46678), help_text='Date due to be returned'),
        ),
    ]
