# Generated by Django 4.2.3 on 2023-07-10 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_loan_date_alter_loan_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter Author date of birth.', null=True, verbose_name='Born'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 17, 38, 58, 999056, tzinfo=datetime.timezone.utc), help_text='Date borrowed'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_back',
            field=models.DateField(default=datetime.datetime(2023, 8, 9, 17, 38, 58, 999381, tzinfo=datetime.timezone.utc), help_text='Date due to be returned'),
        ),
    ]
