# Generated by Django 4.2.3 on 2023-08-17 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_book_author_alter_book_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="date_of_deatg",
            field=models.DateField(
                blank=True,
                help_text="Enter Author date of death.",
                null=True,
                verbose_name="Died",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_back",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 16, 18, 52, 16, 269356, tzinfo=datetime.timezone.utc
                ),
                help_text="Date due to be returned",
            ),
        ),
    ]
