# Generated by Django 4.2.3 on 2023-08-17 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_author_country_author_date_of_deatg_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="date_of_deatg",
            new_name="date_of_deatH",
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_back",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 16, 19, 15, 1, 974681, tzinfo=datetime.timezone.utc
                ),
                help_text="Date due to be returned",
            ),
        ),
    ]
