# Generated by Django 4.2.3 on 2023-08-26 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_rename_date_of_deatg_author_date_of_death_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="date_of_deatH",
            new_name="date_of_death",
        ),
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.TextField(
                help_text="Enter author bio", max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language_code",
            field=models.CharField(
                help_text='Enter 2 letter language code e.g. ("en" for "English")',
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_back",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 25, 10, 14, 59, 204198, tzinfo=datetime.timezone.utc
                ),
                help_text="Date due to be returned",
            ),
        ),
    ]
