# Generated by Django 4.2.3 on 2023-08-27 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0013_rename_date_of_death_author_date_of_death_author_bio_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="catalog.book"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_back",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 26, 16, 37, 0, 528234, tzinfo=datetime.timezone.utc
                ),
                help_text="Date due to be returned",
            ),
        ),
    ]
